sudo: required
dist: trusty
group: deprecated-2017Q4
language: android
jdk: oraclejdk8
before_install:
  - yes | sdkmanager "platforms;android-26"
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-${ANDROID_API}
    - extra-android-m2repository
script:
   - ./gradlew build
